### ISSUE TITLE
Driver does not work with Venus v.2.80-2.83

### ISSUE THREAD

**Issue by Ivo12s** [osaether/dbus-tsmppt#6]
Hello Ole,
As I mentioned, the Morningstar Tristar MPPT-60 works fine for me with Venus v.2.73. I have asked about the possibility of implementing two solar chargers that I have used on the Modification community, so far without success. I have been waiting for the final OS version of VENUS v.2.80-2.81 to test the driver again. Unfortunately it doesn't work. Respectively - the menu for the MPPT IP address is available after the update, but the MPPT charger is not visible on the main screen as well as on the VRM, it does not present the charger there. You mentioned the possibility of embedding a driver for Rapsberry v4 in case it doesn't work. Do you think this is a matter of the new VENUS 2.80 version? Do you think the driver should be rebuilt for the new version?
I actually downgraded the installation back to VENUS v.2.73 to make it work with at least one MPPT.

Regards,

**Comment by osaether** [comment]
Hi @Ivo12s 
Probably the driver must be rebuilt with Venus v2.80. I will see if I can do it in the next few days.

**Comment by mpvader** [comment]
Hi @osaether , two things we changed that come to mind, posting them here just in case they help you: (1) read only rootfs. (2) items-changed, a new D-Bus signal format. But I don't see how that items-changed could affect your driver, since all code is backwards compatible.

**Comment by Ivo12s** [comment]
In case it makes sense, I can perform a complete new installation of v.2.81 and drivers on top of it with backup SD card. At this point, I have performed a standard upgrade to an existing v.2.73 installation. I could test it over the weekend ...

**Comment by osaether** [comment]
Hi @mpvader. Thanks for the suggestions. Right now the problem is that the service is not installed correctly. I have tried different configurations but none work yet. I have looked at some of the bitbake files in the Victron repos but have not found a common setting that works.

Thanks @Ivo12s but I have a VGX device for testing myself but right now it's not looking good. There is a change in how services are handled in the Venus OS that I have not figured out and my experience with the Yocto project/bitbake is limited.

**Comment by osaether** [comment]
Hi @Ivo12s. Please try the file dbus-tsmppt-rpi2-venus-v2.83.tar.gz I uploaded here:
https://github.com/osaether/dbus-tsmppt/releases/tag/v1.18

**Comment by Ivo12s** [comment]
Excellent quick job @osaether . Works as expected.
![image](https://user-images.githubusercontent.com/99555598/154302818-dbaa0e0c-fc79-47fd-9221-11df350e62bc.png)
In case you have some spare time to analyse if exist the solution for two solar chargers 🙏🙏🙏? Thank you a lot anyway!
Installed with actual version 2.84.
![image](https://user-images.githubusercontent.com/99555598/154296230-75d657af-73c2-4f97-b1d2-c22ab74444c5.png)
 

And if need to know - I installed the driver on old version of Raspberry Pi 4 Model B Rev 1.1
